# https://hub.docker.com/r/gitlab/gitlab-ce

version: '2.1'
services:
  gitlab:
    image: gitlab/gitlab-ce:${GITLAB_TAG}
    restart: always
    container_name: gitlab
    hostname: "${GITLAB_HOSTNAME}"
    env_file:
      - ./envfiles/gitlab.env
    ports:
      - '2222:22'
      - 443:443
      - 80:80
    volumes:
      - ./gitlab.rb:/etc/gitlab/gitlab.rb
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - certs:/etc/letsencrypt:ro
    depends_on:
      - redis
      - postgres
      - letsencrypt-dns

  runner:
    image: gitlab/gitlab-runner:${RUNNER_TAG}
    restart: always
    env_file:
      - ./envfiles/runner.env
    volumes:
      - runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock:rw

  postgres:
    image: postgres:${POSTGRES_TAG}
    restart: always
    # https://github.com/docker-library/docs/tree/master/postgres#environment-variables
    env_file:
      - ./envfiles/postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:${REDIS_TAG}
    restart: always
    container_name: gitlab_redis
    command:
      - --loglevel warning
    volumes:
      - redis:/var/lib/redis
    restart: always

  letsencrypt-dns:
    image: adferrand/letsencrypt-dns:${LE_TAG}
    env_file:
      - ./envfiles/le-dns.env
    volumes:
      - ./letsencrypt-domains.conf:/etc/letsencrypt/domains.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/letsencrypt
    restart: always

volumes:
  postgres:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  runner:
  redis:
  certs: